language: node_js
node_js:
  - "7"
  - "6"
  - "4"
os:
  - linux
  - osx

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; export CHROME_BIN=chromium-browser ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sh -e /etc/init.d/xvfb start; fi 
